name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Update system packages
        run: sudo yum update -y

      - name: Install Git
        run: sudo yum install git -y

      - name: Install Docker
        run: sudo yum install docker -y

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Log in to Docker registry
        run: echo ${{ secrets.DOCKER_PASS }} | docker login -u "gerardo0579bvc" --password-stdin docker.io

      - name: Clone repository
        run: |
          sudo mkdir project
          cd project
          sudo apt install git -y
          sudo git clone https://github.com/Gerardo0579-bvc/cloudapp-solutions-site

      - name: Create Dockerfile
        run: |
          echo -e "FROM httpd:2.4\nCOPY ./cloudapp-solutions-site/ /usr/local/apache2/htdocs" > Dockerfile

      - name: Build Docker image
        run: sudo docker build -t cloudappsolutions-image .

      - name: Tag Docker image
        run: sudo docker tag "$(sudo docker images -q cloudappsolutions-image)" gerardo0579bvc/cloudappsolutions-image:version1.0

      - name: Push Docker image
        run: sudo docker push gerardo0579bvc/cloudappsolutions-image:version1.0

      - name: Run Docker container
        run: sudo docker run --name cloudappsolutions-container -p 80:80 -d gerardo0579bvc/cloudappsolutions-image:version1.0
