name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir project
            sudo mkdir project/cloudapp-solutions-site
            sudo mv index.html project/cloudapp-solutions-site
            sudo mv README.md project/cloudapp-solutions-site
            sudo mv css/* project/cloudapp-solutions-site/css
            cd project
            sudo yum update -y
            sudo yum install docker -y
            sudo systemctl start docker
            sudo docker login -u="gerardo0579bvc" -p=${{ secrets.DOCKER_PASS }} docker.io
            sudo echo -e "FROM httpd:2.4\nCOPY ./cloudapp-solutions-site/ /usr/local/apache2/htdocs" > Dockerfiles
            sudo docker build -t cloudappsolutions-image .
            sudo docker tag "$(sudo docker images -q cloudappsolutions-image)" gerardo0579bvc/cloudappsolutions-image:version1.0
            sudo docker push gerardo0579bvc/cloudappsolutions-image:version1.0
            sudo docker run --name cloudappsolutions-container -p 80:80 -d gerardo0579bvc/cloudappsolutions-image:version1.0
            
